production:
    classname:    org.postgresql.Driver
    subprotocol:  postgresql
    host:         localhost
    database:     thejourney
    user:         postgres
    password:     444tundra444

development:
    classname:    org.postgresql.Driver
    subprotocol:  postgresql
    host:         10.0.1.241
    database:     thejourney
    user:         nikebetterworld
    password:     worldbetternike

test:
    classname:    org.postgresql.Driver
    subprotocol:  postgresql
    host:         localhost
    database:     thejourney_test
    user:         postgres


