production:
    classname:    org.postgresql.Driver
    subprotocol:  postgresql
    host:         localhost
    database:     $safeproject$
    user:         postgres

development:
    classname:    org.postgresql.Driver
    subprotocol:  postgresql
    host:         localhost
    database:     $safeproject$_dev
    user:         postgres

test:
    classname:    org.postgresql.Driver
    subprotocol:  postgresql
    host:         localhost
    database:     $safeproject$_test
    user:         postgres


